FROM jlphillips/csci:2024-06-04

RUN mamba install --yes \
    pandas=2.1.4 && \
    mamba clean --all -f -y && \
    fix-permissions "${CONDA_DIR}" && \
    fix-permissions "/home/${NB_USER}" && \
    rm -rf .npm .cache/yarn
