FROM jlphillips/csci:2024-08-07-compbio-prepatches

RUN mamba upgrade --yes \
    gensim && \
    mamba clean --all -f -y

RUN pip install --no-cache-dir \
    accelerate \
    && \
    fix-permissions "${CONDA_DIR}" && \
    fix-permissions "/home/${NB_USER}"
