# Copyright (c) Joshua L. Phillips
# Distributed under the terms of the Modified BSD License.
# Based on the Jupyter Docker Stacks (c) Jupyter Development Team
# Based from: https://github.com/jupyter/docker-stacks
ARG REGISTRY=quay.io
ARG OWNER=jupyter
ARG BASE_IMAGE=$REGISTRY/$OWNER/datascience-notebook:python-3.13
FROM $BASE_IMAGE

LABEL maintainer="Joshua L. Phillips <Joshua.Phillips@mtsu.edu>"

# Fix: https://github.com/hadolint/hadolint/wiki/DL4006
# Fix: https://github.com/koalaman/shellcheck/wiki/SC3014
SHELL ["/bin/bash", "-o", "pipefail", "-c"]

USER root

RUN apt-get update && \
    apt-get install -y \
    unminimize && \
    echo -e "y\ny" | unminimize && \
    apt-get clean && \
    rm -rf /var/lib/apt/lists/*

# Additional tools
RUN apt-get update && \
    apt-get dist-upgrade -y && \
    apt-get install -y software-properties-common && \
    add-apt-repository -y ppa:apptainer/ppa && \
    apt-get update && \
    apt-get install -y \
    apptainer \
    autoconf \
    automake \
    bison \
    clang \
    cmake \
    curl \
    dos2unix \
    dnsutils \
    emacs-nox \
    enscript \
    flex \
    g++ \
    g++-multilib \
    g++-14 \
    g++-14-multilib \
    gcc \
    gcc-multilib \
    gdb \
    graphviz \
    less \
    libopenmpi-dev \
    libtool \
    locales-all \
    make \
    man-db \
    nasm \
    neovim \
    openmpi-bin \
    poppler-utils \
    python3 \
    python3-dev \
    python3-opengl \
    rsync \
    s3cmd \
    ssh \
    tar \
    texlive-science \
    time \
    tmux \
    valgrind \
    wkhtmltopdf \
    xvfb \
    xxd \
    zip && \
    apt-get dist-upgrade -y && \
    apt-get autoremove -y && \
    apt-get clean && \
    rm -rf /var/lib/apt/lists/* && \
    rm -rf /home/${NB_USER}/.launchpadlib && \
    rm -rf "/home/${NB_USER}/.cache/"

USER ${NB_UID}

# Mamba/Conda Tools
RUN mamba install --yes \
    bash_kernel \
    bokeh \
    expect \
    jupyter-server-proxy \
    nltk \
    numpy \
    pandas \
    plotly \
    # Note that protobuf<6 is only to suppress TF warnings (for now - remove later)
    'protobuf<6' \
    pydot \
    python-graphviz \
    wandb \
    websockify \
    xvfbwrapper && \
    mamba clean --all -f -y

# Core Pip Packages
RUN pip install --no-cache-dir \
    --upgrade \
    --upgrade-strategy only-if-needed \
    tensorflow \
    tf-keras \
    keras-tuner \
    keras-cv \
    keras-nlp \
    torch \
    torchaudio \
    torchvision \
    torchmetrics \
    torchtext \
    torchinfo \
    torchview \
    torcheval \
    lightning

RUN pip install --no-cache-dir \
    --upgrade \
    --upgrade-strategy only-if-needed \
    gensim \
    gymnasium \
    jsonargparse[signatures] \
    accelerate \
    datasets \
    diffusers \
    evaluate \
    invisible_watermark \
    langchain \
    langchain-community \
    langchain-mcp-adapters \
    langchain-ollama \
    langchain-openai \
    langgraph \
    langsmith \
    opencv-python \
    opencv-contrib-python \
    safetensors \
    tokenizers \
    torch-geometric \
    transformers
    # pip uninstall -y triton # Needed or not???

RUN fix-permissions "${CONDA_DIR}" && \
    fix-permissions "/home/${NB_USER}"

# Other root operations that can't (or maybe just shouldn't)
# be performed until the packages above are installed...
USER root

# Custom hook to setup home directory
RUN mkdir -p /usr/local/bin/before-notebook.d
COPY config-home.sh /usr/local/bin/before-notebook.d/.

# Remove news extension
RUN jupyter labextension disable "@jupyterlab/apputils-extension:announcements"

# Additional tools
# COPY patches/*.gpg /etc/apt/trusted.gpg.d/.
COPY patches/*.asc /etc/apt/trusted.gpg.d/.
COPY patches/*.list /etc/apt/sources.list.d/.
RUN apt-get update && \
    apt-get install -y \
    default-jre \
    dbus-x11 \
    firefox-esr \
    tigervnc-standalone-server \
    xclip \
    xfce4 \
    xfce4-panel \
    xfce4-session \
    xfce4-settings \
    xorg \
    xubuntu-icon-theme \
    && \
    apt-get clean \
    && \
    apt-get -y -qq remove xfce4-screensaver \
    # chown $HOME to workaround that the xorg installation creates a
    # /home/jovyan/.cache directory owned by root
    && \
    chown -R $NB_UID:$NB_GID $HOME \
    && \
    rm -rf /var/lib/apt/lists/*

# Install:
# VSCode (for IDE)
# RUN curl -fsSL https://code-server.dev/install.sh | sh -s -- --version=4.102.3 && \
#     rm -rf "${HOME}/.cache"
# Code Server and GitHub Copilot (in-line code) extension installation (other notebook)
ARG CODESERVER_VERSION=4.107.1
ARG COPILOT_VERSION=1.388.0
# ARG CODESERVER_VERSION=4.104.3
# ARG COPILOT_VERSION=1.383.1811
# ARG CODESERVER_VERSION=4.104.2
# ARG COPILOT_VERSION=1.376.1794
RUN curl -fsSL https://code-server.dev/install.sh | sh -s -- --version=$CODESERVER_VERSION --method=standalone --prefix=/usr/local && \
    mkdir -p /usr/local/share/code-server/extensions && \
    wget -nv https://marketplace.visualstudio.com/_apis/public/gallery/publishers/ms-vscode/vsextensions/cpptools/1.28.3/vspackage && \
    mv vspackage cpptools.vsix.gz && \
    gunzip cpptools.vsix.gz && \
    code-server --install-extension cpptools.vsix --extensions-dir /usr/local/share/code-server/extensions && \
    rm cpptools.vsix && \
    wget -nv https://marketplace.visualstudio.com/_apis/public/gallery/publishers/ms-vscode/vsextensions/cpptools-extension-pack/1.3.1/vspackage && \
    mv vspackage cpptools-extension-pack.vsix.gz && \
    gunzip cpptools-extension-pack.vsix.gz && \
    code-server --install-extension cpptools-extension-pack.vsix --extensions-dir /usr/local/share/code-server/extensions && \
    rm cpptools-extension-pack.vsix && \
    code-server --install-extension ms-python.python --extensions-dir /usr/local/share/code-server/extensions && \
    code-server --install-extension ms-toolsai.jupyter --extensions-dir /usr/local/share/code-server/extensions && \
    code-server --install-extension ms-toolsai.jupyter-renderers --extensions-dir /usr/local/share/code-server/extensions && \
    cd /usr/local/lib/code-server-$CODESERVER_VERSION/lib/vscode/extensions && \
    ls -d /usr/local/share/code-server/extensions/*/ | xargs -L 1 ln -s
    
# PyCharm and CLion (JetBrains IDEs)
ARG PYCHARM_VERSION=2025.3.1.1
ARG CLION_VERSION=2025.3.1.1
RUN cd /opt && \
    wget -nv https://download.jetbrains.com/python/pycharm-$PYCHARM_VERSION.tar.gz -O pycharm.tar.gz && \
    tar xzf pycharm.tar.gz && \
    rm pycharm.tar.gz && \
    wget -nv https://download-cdn.jetbrains.com/cpp/CLion-$CLION_VERSION.tar.gz -O clion.tar.gz && \
    tar xzf clion.tar.gz && \
    rm clion.tar.gz
COPY <<EOF /usr/share/applications/pycharm.desktop
[Desktop Entry]
Name=PyCharm
GenericName=PyCharm (Python IDE)
Comment=Developer Tools for Python
TryExec=/opt/pycharm-$PYCHARM_VERSION/bin/pycharm
Exec=/opt/pycharm-$PYCHARM_VERSION/bin/pycharm %F
Terminal=false
Type=Application
Keywords=code;editor;development
Icon=/opt/pycharm-$PYCHARM_VERSION/bin/pycharm.png
MimeType=application/xml
Categories=Development
EOF
COPY <<EOF /usr/share/applications/clion.desktop
[Desktop Entry]
Name=CLion
GenericName=CLion (C/C++ IDE)
Comment=Developer Tools for C/C++
TryExec=/opt/clion-$CLION_VERSION/bin/clion
Exec=/opt/clion-$CLION_VERSION/bin/clion %F
Terminal=false
Type=Application
Keywords=code;editor;development
Icon=/opt/clion-$CLION_VERSION/bin/clion.png
MimeType=application/xml
Categories=Development
EOF

# NodeJS Support
ENV NVM_DIR=/opt/nvm
RUN mkdir -p /opt/nvm && \
    curl -o- https://raw.githubusercontent.com/nvm-sh/nvm/v0.40.3/install.sh | bash && \
    bash -c "source $NVM_DIR/nvm.sh && nvm install 22"
RUN <<EOF
echo -e "export NVM_DIR=\"/opt/nvm\"" >> /home/${NB_USER}/.bashrc
echo -e "[ -s \"$NVM_DIR/nvm.sh\" ] && \\. \"$NVM_DIR/nvm.sh\"  # This loads nvm" >> /home/${NB_USER}/.bashrc
echo -e "[ -s \"$NVM_DIR/bash_completion\" ] && \\. \"$NVM_DIR/bash_completion\"  # This loads nvm bash_completion" >> /home/${NB_USER}/.bashrc
EOF
CMD ["bash", "-c", "source $NVM_DIR/nvm.sh && exec start-notebook.py", "--"]

# GitHub Copilot CLI (and language server) installation
RUN bash -c "source $NVM_DIR/nvm.sh && npm install -g \
    @github/copilot \
    @github/copilot-language-server"

# NVIM GitHub Copilot Plugin
RUN git clone https://github.com/github/copilot.vim \
    /usr/share/nvim/runtime/pack/github/start/copilot.vim

# Emacs Configuration for Copilot
COPY <<EOF /etc/emacs/site-start.d/98straight.el
;; Package management with straight.el and use-package
(defvar bootstrap-version)
(let ((bootstrap-file
       (expand-file-name
        "straight/repos/straight.el/bootstrap.el"
        (or (bound-and-true-p straight-base-dir)
            user-emacs-directory)))
      (bootstrap-version 7))
  (unless (file-exists-p bootstrap-file)
    (with-current-buffer
        (url-retrieve-synchronously
         "https://raw.githubusercontent.com/radian-software/straight.el/develop/install.el"
         'silent 'inhibit-cookies)
      (goto-char (point-max))
      (eval-print-last-sexp)))
  (load bootstrap-file nil 'nomessage))
EOF
COPY <<EOF /etc/emacs/site-start.d/99copilot.el
;; GitHub Copilot Integration
(use-package copilot
  :straight (:host github :repo "copilot-emacs/copilot.el" :files ("*.el"))
  :ensure t)

(add-hook 'prog-mode-hook 'copilot-mode)
(define-key copilot-completion-map (kbd "<tab>") 'copilot-accept-completion)
(define-key copilot-completion-map (kbd "TAB") 'copilot-accept-completion)
EOF

# GitHub Copilot Support for VSCode
# (Note that the separate package is no longer required in VS Code, it's already integrated)
# Note that the ARG settings are in the previous notebook, so need to match accordingly...
ARG CODESERVER_VERSION=4.107.1
ARG COPILOT_VERSION=1.388.0
# ARG CODESERVER_VERSION=4.104.3
# ARG COPILOT_VERSION=1.383.1811
# RUN wget -nv https://marketplace.visualstudio.com/_apis/public/gallery/publishers/GitHub/vsextensions/copilot/$COPILOT_VERSION/vspackage && \
#     mv vspackage github-copilot.vsix.gz && \
#     gunzip github-copilot.vsix.gz && \
#     code-server --install-extension github-copilot.vsix --extensions-dir /usr/local/share/code-server/extensions && \
#     rm github-copilot.vsix && \
#     cd /usr/local/lib/code-server-$CODESERVER_VERSION/lib/vscode/extensions && \
#     ls -d /usr/local/share/code-server/extensions/github.copilot*/ | xargs -L 1 ln -s

# Cursor
RUN wget -nv "https://downloads.cursor.com/production/56f0a83df8e9eb48585fcc4858a9440db4cc7771/linux/x64/deb/amd64/deb/cursor_2.1.50_amd64.deb" && \
    apt-get install -y ./cursor_2.1.50_amd64.deb && \
    rm cursor_2.1.50_amd64.deb && \
    apt-get clean && \
    rm -rf /var/lib/apt/lists/*

# Windsurf
RUN wget -qO- "https://windsurf-stable.codeiumdata.com/wVxQEIWkwPUEAGf3/windsurf.gpg" | gpg --dearmor > windsurf-stable.gpg && \
    install -D -o root -g root -m 644 windsurf-stable.gpg /etc/apt/keyrings/windsurf-stable.gpg && \
    echo "deb [arch=amd64 signed-by=/etc/apt/keyrings/windsurf-stable.gpg] https://windsurf-stable.codeiumdata.com/wVxQEIWkwPUEAGf3/apt stable main" | sudo tee /etc/apt/sources.list.d/windsurf.list > /dev/null && \
    rm -f windsurf-stable.gpg && \
    apt-get update && \
    apt-get install windsurf && \ 
    apt-get clean && \
    rm -rf /var/lib/apt/lists/*

# Qwen Code CLI installation
RUN bash -c "source $NVM_DIR/nvm.sh && \
    npm install -g @qwen-code/qwen-code"

# Opencode CLI installation
RUN bash -c "source $NVM_DIR/nvm.sh && \
    npm install -g opencode-ai"

# Cline CLI installation
RUN bash -c "source $NVM_DIR/nvm.sh && \
    npm install -g cline"

# Cleanup
RUN rm -rf "${HOME}/.cache" && \
    rm -rf "${HOME}/.npm" && \
    rm -rf "${HOME}/.local" && \
    fix-permissions "${CONDA_DIR}" && \
    fix-permissions "/home/${NB_USER}"

# Switch back to user for final env
# configuration...
USER ${NB_UID}

# JS-Proxy package(s) configuration:
# jupyter_remote_desktop_proxy (for Desktop)
# jupyter_codeserver_proxy (for IDE)
# ENV CODE_WORKINGDIR="${HOME}"
COPY ./dist/jupyter_codeserver_proxy-1.0b3-py3-none-any.whl \
     ./dist/jupyter_remote_desktop_proxy-3.0.2.dev0-py3-none-any.whl \
     /${HOME}/
RUN pip install --no-cache-dir \
    --upgrade \
    --upgrade-strategy only-if-needed \
    *.whl && \
    rm *.whl && \
    fix-permissions "${CONDA_DIR}" && \
    fix-permissions "/home/${NB_USER}"

# AIDER - probably best method for installation
RUN curl -LsSf https://aider.chat/install.sh | XDG_BIN_HOME=/opt/conda/bin XDG_DATA_HOME=/opt/conda/share sh

# Notebook Intelligence
RUN pip install --no-cache-dir \
    --upgrade \
    --upgrade-strategy only-if-needed \
    notebook-intelligence && \
    fix-permissions "${CONDA_DIR}" && \
    fix-permissions "/home/${NB_USER}"
